# The proposal
<!--
This is where the proposal should be outlined. 
-->

## Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

Project member Aaron Jacobs wrote a demo-quality external sampling profiler for R
earlier this year, which is available [on GitHub](https://github.com/atheriel/rtrace).
The demo is also capable of outputting "mixed-mode" combinations of the R and
C/C++ stacks, in line with the goals of the **jointprof** package.

This demo (1) proves that this is indeed possible for R; and (2) points the way
to the technologies that are needed to make it work.

We propose to turn this demo-quality project into a robust set of tools that can
be used by the wider community, and especially in **jointprof**.

A larger goal of this proposal is to help move the **jointprof** project
forward. Provided that this project can meet its goals, the resulting library
could replace the use of `pprof` in the **jointprof** package, giving that
project three desirable features that it does not currently have:

* Support for profiling external R programs, which would unlock the ability to
  [profile multiprocess-style parallel programs](https://github.com/r-prof/jointprof/issues/10).

* [Support for Windows](https://github.com/r-prof/jointprof/issues/29); and

* [Better profiling in the presence of R's lazy evaluation](https://github.com/r-prof/jointprof/issues/34).

In addition, it would remove the need for end users to install and manage a Go
toolchain.

## Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

In order to make the existing demo more widely useful, we propose to break it
into two components: a command-line tool for users and a C library that backs
this program and other interfaces. This will involve:

* Refactoring the existing code to be more robust, handle more diverse R
  environments, and report errors to the caller; and

* Be sufficiently portable to work on any Linux distribution and any
  sufficiently recent version of R.

It is our view that a tool for R users is unlikely to be successful if it does
not have an R-level interface. To that end, the second major goal of this
project would be to create an R package backed by the same library. Provided
that this library is relatively portable and written in C, we believe that such
a package would be admissible to CRAN.

The delivery of

<!-- > \(1) a C library, (2) a command-line program; and (3) an R package for Linux -->
<!-- > that supports sampling R stacks -->
1. \(i) a C library, (ii) a command-line program; and (iii) an R package for
   Linux

is **the minimum viable product (MVP) of this proposal**.

In addition to this MVP, the secondary goal of this proposal is

<!-- > to add sampling of C/C++ stacks to this library, incorporating the lessons -->
<!-- > learned from the **jointprof** package -->
2. To add sampling of C/C++ stacks to this library, incorporating the lessons
   learned from the **jointprof** package.

Sampling of C/C++ stacks is already part of the existing demo; however,
collating these and the R-level stacks does not yet work reliably. In addition,
we are unsure of whether the existing approach can be made to work on non-Linux
platforms; Jeroen Ooms has provided some guidance on this question and possible
alternatives.

Finally, we propose to "port" the tool so that it works in two other common R
environments:

3. Under Docker. Although Docker is, of course, Linux, its use of process
   namespaces render the existing demo nonfunctional. Yet Dockerized R is very
   likely the medium-term future of production in R. The
   [Pyflame](https://github.com/uber/pyflame) profiler for Python has shown that
   it is possible to circumvent the namespace issues; we feel we could make the
   same approach work for this project.

4. Under Windows. Although there are likely fewer "production" deployments of R
   on Windows, it is a major platform for R users. The
   [rbspy](https://rbspy.github.io/) profiler for Ruby has shown that it is
   possible to support Windows in this way; we feel we could learn from them and
   make the same approach work for this project.

## Priorities

The authors of this proposal are open to comments from the reviewers on what
features ought to be prioritized.

## Alternatives

A new, external sampling profiler is not the only way to achieve live, opt-in
profiling of running R programs. It would also be possible to modify R itself to
switch on profiling in response to some kind of IPC, such as a Unix signal. The
authors have not raised this suggestion to the R developers, but it is still
possible to do so.

However, there are major drawbacks to such an undertaking: it would require
modifying R itself, perhaps in ways that have an undesirable impact on its
complexity or performance, and would only allow code running under new versions
of R (perhaps quite some time from now) to be profiled in this way. As a result,
we believe a new tool is a better way to accomplish the project's goals.
