# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

## Definition of done
<!-- 
What does success look like? 
-->

Success can be defined as full delivery of the artifacts and outcomes discussed
in the [Technical delivery](#technical-delivery) section above. Partial success
can also be defined in this manner as delivery of some but not all these
artifacts and outcomes.

## Measuring success
<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->

As mentioned in the [Technical delivery](#technical-delivery) section, we can
use the following markers:

* Release of version 0.1 of the proposed MVP library, command-line program, and
  R package.

* Release of the MVP artifacts with support for Docker.

* Release of the MVP artifacts with support for Windows.

* Release of the MVP artifacts with support for mixed-mode R and C/C++ stack
  sampling.

* Release of a version of **jointprof** using the new library to CRAN.

* Finally, release of e.g. blog posts, screencasts, or other public testimonials
  on the use of this project.

## Future work
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->

Our suggested future work would include

* Packaging of the command-line tool for various Linux distributions, first and
  foremost the Debian project (and downstream distributions, including Ubuntu).
  This would improve the ease with which this tool would be available in these
  environments.

* Support for macOS. Although it is unlikely that many users are running
  production workloads on macOS, it is a popular distribution for R developers.

* Support for Solaris and other less-popular platforms, such as FreeBSD.

## Key risks
<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->

* It may turn out to be too difficult to support either R stack sampling or
  C/C++ stack sampling on Windows. This would be a major blow to the aims of the
  project, but the MVP of this proposal would still be deliverable.

* It may turn out to be too difficult or impossible to fully reconcile the R and
  C/C++ stacks when outputting mixed-mode samples. If this were to be the case,
  it should be possible to either fall back on R-only sampling or perform
  best-effort reconciliation.

* Lastly, the project could face significant delays if project member Aaron
  Jacobs is unable to work on implementing the deliverables. Should this come to
  pass, it may be possible to scope out the implementation work for assignment
  to another member of the community.
