# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

The existing code is already on GitHub, and that platform is intended to be
where all development takes place. Since the goals of this proposal are
relatively well-defined, GitHub issues can be used to track progress and provide
public visibility of progress. Moreover, the use of GitHub will give us access
to tools such as Travis-CI, which can be used to ensure that the code will work
under a variety of environments.

In addition, we have corresponded with Kirill Müller on the relationship between
the proposed project and other packages and tools in the R ecosystem. Because of
this, we believe that our views of future success are aligned with other
projects and proposals, and that there are a few points of external reference
against which to gauge the relevance of design or technical decisions.

### Licensing

Since the demo already contains portions of the source code of R itself and this
is unlikely to change in its transition to a library, it is very likely it must
fall under the same license, GPLv2. This is a common license in the R community,
so this choice is not expected to cause any friction.

## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

The timeline of the project is intended to be short:

1. Delivery of the proposed MVP: refactoring of the demo into a portable C
   program and library for Linux, plus an R package interface. Estimated to take
   up to two weeks. This would be signified by a "0.1" release of these
   artifacts.

2. Delivery of the proposed port to Docker. Estimated to take a few days.

3. Delivery of the proposed port to Windows of the R sampling portion of the
   library. Estimated to take up to two weeks.

4. Delivery of support for mixed-mode R and C/C++ stack sampling, again
   Linux-first. Estimated to take up to a month, and would be signified by a
   second release of the artifacts.

5. Delivery of wrap-up work, including a substantive blog post, integration into
   **jointprof**, and submission of one or more packages to CRAN. Estimated to
   take up to two weeks.

Given the plan to work nearly full-time on this proposal, we believe this should
be possible.

## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

In order to publicise the project and ensure that R users can actively benefit
from it, we propose writing a blog post, ideally for the R Consortium,
explaining how to use the tools provided by the project.

Since the goals of the project are relatively narrow and use cases are fairly
narrow, we believe a single tutorial/evangelist-style post will be the most
appropriate reference point for the community.

In addition, the authors of this proposal intend to publicize this work at all
available opportunity: by submitting talks to UseR!, producing blog posts,
demos, use cases, and possibly screencasts to be shared on Twitter and other
platforms.
